### PR TITLE
update readme

### PR DESCRIPTION
**Pull request by dbu**
adding some information to the readme.

should you not contribute the helpers to xamin/handlebars.php ? they are not symfony specific, after all...

also, if there is a way to add own helpers in the bundle, this should be documented.

### CODE REVIEW

**Comment by mfeltscher** [comment]
I was thinking about putting these helpers into a separate bundle, I think it would make more sense since it's more of a extension. What do you think?

**Comment by dbu** [comment]
a bundle would make no sense. either xamin/handlebars.php or make a simple repository `smartive/handlebars-helpers` - then again at this point not so sure if its worth the effort at this point.

**Comment by mfeltscher** [comment]
These helpers are non-official Handlebars helpers - see http://assemble.io/helpers/
Therefore I don't think they belong in `xamin/handlebars.php`

**Comment by mfeltscher** [comment]
@dbu: Could you, just for the moment, adjust the README to just have the first part about `xamin/handlebars.php` in it? I will remove the helpers and add documentation on how you can add your own helpers.

**Comment by dbu** [comment]
updated.

**Pull request merged**
